<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeDesignPlus.Net.Microservice.Services.Application\CodeDesignPlus.Net.Microservice.Services.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\errors.*.json" LogicalName="%(Filename)%(Extension)" WithCulture="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CodeDesignPlus.Net.Exceptions" Version="1.0.0-beta.13390" />
  </ItemGroup>
</Project>