name: Build .Net

on:
  push:
    branches:
      - main
      - rc
      - dev
      - feature/*
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  build:
    uses: codedesignplus/workflows/.github/workflows/build-microservice.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Services
      microservice-name: ms-services
    secrets: inherit