name: Build and Push Container Image

on:
  push:
    branches:
      - main
      - rc
      - dev
      - feature/*

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  ci:
    uses: codedesignplus/workflows/.github/workflows/container-image.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Services
      microservice-name: ms-services
    secrets: inherit